"use client";

import type { ReactNode } from "react";
import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { ArrowUpRight, BookOpen, Cable, CheckCircle2, Code2, Factory, MapPin, RadioTower, Wrench } from "lucide-react";
import Link from "next/link";
import { siteConfig } from "@/content/site-config";
import { ContactForm } from "@/components/forms/contact-form";

const ease = [0.16, 1, 0.3, 1] as const;
const pageCodes = { experience:"02", about:"03", skills:"04", now:"N", contact:"06" };

function PageHero({ code, title, accent, copy }: { code:string; title:string; accent:string; copy:string }) {
  const reduce = useReducedMotion(); const { scrollYProgress } = useScroll(); const y = useTransform(scrollYProgress,[0,.35],[0,70]);
  return <section className="relative min-h-[48svh] overflow-hidden border-b border-border px-5 pb-14 pt-16 sm:px-8 sm:pb-20 sm:pt-20">
    <motion.span aria-hidden="true" style={{y:reduce?0:y}} className="absolute right-2 top-3 font-display text-[clamp(7rem,24vw,18rem)] font-black leading-none text-text/[.045] dark:text-text/[.035]">{code}</motion.span>
    <div className="relative mx-auto max-w-6xl"><motion.p initial={reduce?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.55,ease}} className="font-mono text-xs uppercase tracking-[.2em] text-primary">Rakesh Kumar Behera / route {code}</motion.p><div className="mt-8 overflow-hidden"><motion.h1 initial={reduce?false:{y:"106%"}} animate={{y:0}} transition={{duration:.78,ease}} className="max-w-4xl font-display text-[clamp(3rem,7vw,6rem)] font-extrabold leading-[.88] tracking-[-.05em] text-text">{title}</motion.h1></div><motion.p initial={reduce?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.65,ease,delay:.18}} className="mt-6 font-display text-[clamp(1.3rem,2.4vw,2.1rem)] font-semibold text-primary">{accent}</motion.p><motion.p initial={reduce?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.65,ease,delay:.27}} className="mt-4 max-w-[66ch] text-body-lg text-text-muted">{copy}</motion.p></div>
  </section>;
}
function Label({children}:{children:ReactNode}){return <p className="mb-8 flex items-center gap-3 font-mono text-xs uppercase tracking-[.18em] text-primary"><span className="h-px w-8 bg-primary"/>{children}</p>}
function Reveal({children,className="",delay=0}:{children:ReactNode;className?:string;delay?:number}){return <motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.22}} transition={{duration:.65,ease,delay}} className={className}>{children}</motion.div>}

export function AboutExperience(){const a=siteConfig.about;return <><PageHero code={pageCodes.about} title="ABOUT THE ENGINEER." accent="Curious across circuits, controls and code." copy={a.intro}/><section className="mx-auto max-w-6xl px-5 py-20 sm:px-8 sm:py-24"><Label>the through-line</Label><div className="grid gap-6 lg:grid-cols-2"><Reveal className="depth-panel rounded-2xl border border-border bg-surface p-7 sm:p-9"><Cable className="h-7 w-7 text-primary"/><h2 className="mt-7 font-display text-h2 font-bold text-text">Electrical thinking</h2><p className="mt-4 text-body-lg text-text-muted">{a.whyEngineering}</p></Reveal><Reveal delay={.08} className="depth-panel rounded-2xl bg-text p-7 text-bg sm:p-9"><Code2 className="h-7 w-7 text-primary"/><h2 className="mt-7 font-display text-h2 font-bold">Software building</h2><p className="mt-4 text-body-lg text-bg/65">{a.industrialToSoftware}</p></Reveal></div></section><section className="border-y border-border bg-surface px-5 py-20 sm:px-8"><div className="mx-auto max-w-6xl"><Label>operating rules</Label><div className="divide-y divide-border border-y border-border">{a.principles.map((p,i)=><Reveal key={p} delay={i*.05} className="grid gap-3 py-6 sm:grid-cols-[4rem_1fr]"><span className="font-mono text-primary">0{i+1}</span><p className="font-display text-h2 font-semibold text-text">{p}</p></Reveal>)}</div></div></section></>}

export function ExperienceExperience(){return <><PageHero code={pageCodes.experience} title="FIELD EXPERIENCE." accent="Inspection discipline, automation training and heavy electrical systems." copy="Verified industrial work and the lessons that shaped how I approach reliability."/><section className="mx-auto max-w-6xl px-5 py-20 sm:px-8 sm:py-24"><Label>signal path / 2024 to 2026</Label><div className="relative"><motion.div initial={{scaleY:0}} whileInView={{scaleY:1}} viewport={{once:true}} transition={{duration:1.2,ease}} className="absolute bottom-0 left-[.38rem] top-0 w-px origin-top bg-primary sm:left-[11.35rem]"/><ol className="space-y-12">{siteConfig.experience.map((item,i)=><Reveal key={item.company} delay={i*.04} className="relative grid gap-3 pl-9 sm:grid-cols-[10rem_1fr] sm:gap-10 sm:pl-0"><span className="absolute left-0 top-2 h-3 w-3 rounded-full border-2 border-primary bg-bg sm:left-[11rem]"/><p className="font-mono text-xs uppercase tracking-[.13em] text-text-muted">{item.period}</p><div className="sm:pl-9"><h2 className="font-display text-h2 font-semibold text-text">{item.role}</h2><p className="mt-1 text-primary">{item.company} / {item.location}</p><p className="mt-4 max-w-[62ch] text-text-muted">{item.reflection}</p><div className="mt-4 flex flex-wrap gap-2">{item.systems.map(s=><span key={s} className="rounded-md bg-surface-2 px-3 py-1.5 text-xs text-text-muted">{s}</span>)}</div></div></Reveal>)}</ol></div></section></>}

const skillIcons=[Factory,Code2,Wrench];
export function SkillsExperience(){const groups=[["Electrical & Industrial",siteConfig.skills.electricalIndustrial],["Software & Systems",siteConfig.skills.softwareSystems],["Tools & Workflow",siteConfig.skills.toolsWorkflow]] as const;return <><PageHero code={pageCodes.skills} title="CAPABILITY MAP." accent="Practical context, never inflated percentages." copy={siteConfig.skills.intro}/><section className="mx-auto max-w-6xl px-5 py-20 sm:px-8 sm:py-24"><div className="grid gap-6 lg:grid-cols-3">{groups.map(([title,skills],index)=>{const Icon=skillIcons[index];return <Reveal key={title} delay={index*.07} className="depth-panel overflow-hidden rounded-2xl border border-border bg-surface"><div className="flex items-center justify-between border-b border-border p-6"><Icon className="h-6 w-6 text-primary"/><span className="font-mono text-xs text-text-muted">0{index+1}</span></div><div className="p-6"><h2 className="font-display text-h2 font-semibold text-text">{title}</h2><ul className="mt-7 space-y-5">{skills.map((skill,i)=><li key={skill.name}><div className="flex items-end justify-between gap-3"><span className="text-sm text-text">{skill.name}</span><span className="font-mono text-[.58rem] uppercase tracking-wider text-text-muted">{skill.level}</span></div><div className="mt-2 h-px bg-border"><motion.div initial={{scaleX:0}} whileInView={{scaleX:1}} viewport={{once:true}} transition={{duration:.8,ease,delay:i*.05}} className="h-px origin-left bg-primary" style={{width:`${48+(i%4)*12}%`}}/></div></li>)}</ul></div></Reveal>})}</div></section></>}

export function NowExperience(){const now=siteConfig.now;return <><PageHero code={pageCodes.now} title="NOW / NEXT." accent="A compact engineering notebook." copy={`Current focus and build notes. Updated ${now.updated}.`}/><section className="mx-auto max-w-6xl px-5 py-20 sm:px-8 sm:py-24"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><Reveal><Label>current channels</Label>{now.focus.map((item,i)=><motion.div whileHover={{x:6}} key={item} className="flex items-center gap-4 border-b border-border py-4"><span className="h-2.5 w-2.5 rounded-full bg-primary"/><p className="text-text">{item}</p><span className="ml-auto font-mono text-xs text-text-muted">0{i+1}</span></motion.div>)}</Reveal><Reveal delay={.08}><Label>logbook</Label><div className="rounded-2xl border border-border bg-surface p-7"><BookOpen className="h-6 w-6 text-primary"/>{now.log.map((entry,i)=><div key={i} className="mt-7 border-t border-border pt-6"><p className="font-mono text-xs uppercase tracking-wider text-primary">{entry.date}</p><p className="mt-3 text-body-lg text-text-muted">{entry.note}</p></div>)}</div></Reveal></div></section></>}

export function ContactExperience(){const p=siteConfig.person;return <><PageHero code={pageCodes.contact} title="OPEN CHANNEL." accent="Tell me what needs to work." copy="For graduate electrical roles, quality, automation, maintenance, software opportunities and serious collaborations."/><section className="mx-auto max-w-6xl px-5 py-20 sm:px-8 sm:py-24"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><Reveal><Label>connection status</Label><div className="rounded-2xl bg-text p-7 text-bg"><RadioTower className="h-7 w-7 text-primary"/><p className="mt-7 font-mono text-xs uppercase tracking-[.16em] text-bg/50">location</p><p className="mt-2 text-xl">{p.location}</p><p className="mt-6 font-mono text-xs uppercase tracking-[.16em] text-bg/50">availability</p><p className="mt-2 text-xl">{p.availability}</p><div className="mt-8 flex items-center gap-2 border-t border-bg/15 pt-5 text-sm text-bg/65"><CheckCircle2 className="h-4 w-4 text-primary"/>Channel ready</div></div></Reveal><Reveal delay={.08} className="rounded-2xl border border-border bg-surface p-6 sm:p-9"><Label>message console</Label><ContactForm/></Reveal></div></section></>}
